### ISSUE TITLE
Type System.Type not found

### ISSUE THREAD

**Issue by Jamesits** [robinzevallos/Kasay.DependencyProperty.WPF.Fody#1]
Got the following error across 1.0.0-1.0.2. I'm not sure why it happens.

```
Error		Fody: An unhandled exception occurred:
Exception:
Failed to execute weaver <redacted>\packages\Kasay.DependencyProperty.WPF.Fody.1.0.2\build\Kasay.DependencyProperty.WPF.Fody.dll
Type:
System.Exception
StackTrace:
   at InnerWeaver.ExecuteWeavers()
   at InnerWeaver.Execute()
Source:
FodyIsolated
TargetSite:
Void ExecuteWeavers()
Type System.Type not found.
Type:
System.NullReferenceException
StackTrace:
   at Kasay.FodyHelpers.HelpersExtension.IfNull[T](T reference, String message)
   at Kasay.FodyHelpers.ModuleDefinitionExtension.GetTypeReference(ModuleDefinition moduleDefinition, String fullname)
   at Kasay.FodyHelpers.ModuleDefinitionExtension.GetMethodReference(ModuleDefinition moduleDefinition, String fullnameType, String nameMethod)
   at Kasay.DependencyProperty.WPF.Fody.DependencyPropertyFactory.EqualDependencyPropertyField()
   at Kasay.DependencyProperty.WPF.Fody.DependencyPropertyFactory..ctor(AssemblyFactory baseAssembly, PropertyDefinition propertyDefinition)
   at ModuleWeaver.SetDependencyPropertyToTypes()
   at ModuleWeaver.Execute()
   at InnerWeaver.ExecuteWeavers()
Source:
Kasay.FodyHelpers
TargetSite:
T IfNull[T](T, System.String)		
```

**Comment by robinzevallos** [comment]
Try again with the new update.

**Comment by Jamesits** [comment]
Sorry for my late reply. Version 1.0.3 still have the exact same error.
